In [1]:
!pip install pandas
import os
import numpy as np
import pandas


In [63]:
dis_whole_data_path = [
    "data/irish-dis-measure-vae-train-whole.npy",
    "data/irish-dis-measure-vae-validate-whole.npy",
    "data/irish-dis-measure-vae-test-whole.npy"
]

whole_data_path = [
    "data/irish-measure-vae-train-whole.npy",
    "data/irish-measure-vae-validate-whole.npy",
    "data/irish-measure-vae-test-whole.npy"
]

data_path = ["data/irish_train.npy",
              "data/irish_validate.npy",
              "data/irish_test.npy"]

chord_rhythm_path= ["data/irish_train_chord_rhythm.npy",
              "data/irish_validate_chord_rhythm.npy",
              "data/irish_test_chord_rhythm.npy"]

In [64]:
irish_train = np.load(data_path[0], allow_pickle = True)
irish_dis_whole = np.load(dis_whole_data_path[0],allow_pickle = True)
irish_whole = np.load(whole_data_path[0],allow_pickle = True)

In [29]:
irish_train_rhythm_pitch = np.load(chord_rhythm_path[0], allow_pickle = True)

In [43]:
irish_train_rhythm_pitch[0][3]
#notes(old), xpitch, xrhythm

8

In [97]:
len(irish_train[0]['notes'])


768

In [74]:
lengths = []
for song in irish_train:
    song2 = []
    for note in song['notes']:
        if note != 128:
            song2.append(note)
    lengths.append(len(song2))

print(set(lengths))

{14, 15, 16, 18, 22, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 

In [79]:
len(irish_dis_whole)

39798

In [68]:
len(irish_whole.tolist()['gd'][0])

16

In [6]:
concat_gd = np.concatenate([a for a in irish_whole.tolist()['gd'][0]])
print(concat_gd)

[ 70 128 128 128 128 128 128 128 128  72 128 128  73 128 128  72 128 128
  73 128 128  75 128 128  77 128 128 128 128 128  75 128 128  80 128 128
  80 128 128  77 128 128  75 128 128  78 128 128  77 128 128  73 128 128
  70 128 128  72 128 128  73 128 128  75 128 128  77 128 128  79 128 128
  80 128 128 128 128 128  82 128 128  79 128 128  80 128 128  77 128 128
  75 128 128  72 128 128  70 128 128 128 128 128 128 128 128  72 128 128
  73 128 128  72 128 128  73 128 128  75 128 128  77 128 128 128 128 128
  75 128 128  80 128 128  80 128 128  77 128 128  75 128 128  78 128 128
  77 128 128  73 128 128  70 128 128  72 128 128  73 128 128  75 128 128
  77 128 128  79 128 128  80 128 128  77 128 128  75 128 128  72 128 128
  73 128 128  70 128 128  70 128 128  68 128 128  70 128 128 128 128 128
 128 128 128  72 128 128  73 128 128  72 128 128  73 128 128  75 128 128
  77 128 128 128 128 128  75 128 128  80 128 128  80 128 128  77 128 128
  75 128 128  78 128 128  77 128 128  73 128 128  7

In [7]:
concat_gd[0] == int(70)

True

In [8]:
list(np.load('res-exp-sketchnet_control_mixture_2.npy', allow_pickle= True))[0].keys()

dict_keys(['past1', 'past2', 'future1', 'future2', 'inpaint', 'gd1', 'gd2', 'acc', 'nll'])

In [9]:
list(np.load('res-exp-sketchnet_control_mixture_2.npy', allow_pickle= True))[0]['future2']


array([[[ 74, 128, 128, 128, 128, 128,  79, 128, 128, 128,  77, 128,
          76, 128, 128, 128, 128, 128,  79, 128,  81, 128,  79, 128],
        [ 76, 128, 128, 128,  74, 128,  72, 128,  74, 128,  76, 128,
          74, 128, 128, 128,  72, 128,  71, 128, 128, 128,  74, 128],
        [ 72, 128, 128, 128, 128, 128,  69, 128, 128, 128,  70, 128,
          72, 128,  74, 128,  72, 128,  81, 128, 128, 128, 128, 128],
        [ 81, 128,  83, 128,  81, 128,  79, 128, 128, 128,  78, 128,
          79, 128, 128, 128, 128, 128,  74, 128, 128, 128, 128, 128],
        [ 86, 128, 128, 128, 128, 128, 128, 128, 128,  84, 128, 128,
          83, 128, 128, 128,  84, 128,  86, 128, 128, 128,  84, 128],
        [ 82, 128, 128, 128,  79, 128,  76, 128, 128, 128,  72, 128,
          77, 128, 128, 128, 128, 128,  81, 128, 128, 128, 128, 128]]])

In [10]:
import pretty_midi as pyd
import numpy as np
import os
import random
import music21 as m21
from loader.chordloader import Chord_Loader
import copy


class MIDI_Render:
    def __init__(self, datasetName, minStep = 0.03125):
        self.datasetName = datasetName
        self.minStep = minStep
    def gd2midi(self, data, recogLevel = "Mm", output = "test.mid"):
            gen_midi = pyd.PrettyMIDI()
            melodies = pyd.Instrument(program = pyd.instrument_name_to_program('Acoustic Grand Piano'))
            chords = pyd.Instrument(program = pyd.instrument_name_to_program('Acoustic Grand Piano'))
            if self.datasetName == "Nottingham":
                # 130 one hot vectors 
                # 0-127 for pitch
                # 128 for hold 129 for rest
                rest_pitch = 129
                hold_pitch = 128
                cl = Chord_Loader(recogLevel = recogLevel)
                time_shift = 0.0
                local_duration = 0
                prev = "NC"
                for chord in data["chords"]:
                    if chord == "":
                        continue
                    chord = cl.index2name(x = int(chord))
                    if chord == prev:
                        local_duration += 1
                    else:
                        if prev == "NC":
                            prev = chord
                            time_shift += local_duration * self.minStep
                            local_duration = 1
                        else:
                            i_notes = cl.name2note(name = prev, stage = 4)
                            for i_note in i_notes:
                                i_note = pyd.Note(velocity = 100, pitch = i_note, 
                                start = time_shift, end = time_shift + local_duration * self.minStep)
                                chords.notes.append(i_note)
                            prev = chord
                            time_shift += local_duration * self.minStep
                            local_duration = 1
                if prev != "NC":
                    i_notes = cl.name2note(name = prev, stage = 4)
                    for i_note in i_notes:
                        i_note = pyd.Note(velocity = 100, pitch = i_note, 
                        start = time_shift, end = time_shift + local_duration * self.minStep)
                        chords.notes.append(i_note)
                gen_midi.instruments.append(chords)

                time_shift = 0.0
                local_duration = 0
                prev = rest_pitch
                for note in data:
                    note = int(note)
                    if note < 0 or note > 129:
                        continue
                    if note == hold_pitch:
                        local_duration += 1
                    elif note == rest_pitch:
                        time_shift += self.minStep
                    else:
                        if prev == rest_pitch:
                            prev = note
                            local_duration = 1
                        else:
                            i_note = pyd.Note(velocity = 100, pitch = prev, 
                                start = time_shift, end = time_shift + local_duration * self.minStep)
                            melodies.notes.append(i_note)
                            prev = note
                            time_shift += local_duration * self.minStep
                            local_duration = 1
                if prev != rest_pitch:
                    i_note = pyd.Note(velocity = 100, pitch = prev, 
                                start = time_shift, end = time_shift + local_duration * self.minStep)
                    melodies.notes.append(i_note)
                gen_midi.instruments.append(melodies)
                gen_midi.write(output)
                print("finish render midi on " + output)
            if self.datasetName == "Irish":
                # 130 one hot vectors 
                # 0-127 for pitch
                # 128 for hold 129 for rest
                rest_pitch = 129
                hold_pitch = 128
                local_duration = 0
                time_shift = 0.0
                local_duration = 0
                prev = rest_pitch
                for note in data:
                    note = int(note)
                    if note < 0 or note > 129:
                        continue
                    if note == hold_pitch:
                        local_duration += 1
                    elif note == rest_pitch:
                        time_shift += self.minStep
                    else:
                        if prev == rest_pitch:
                            prev = note
                            local_duration = 1
                        else:
                            i_note = pyd.Note(velocity = 100, pitch = prev, 
                                start = time_shift, end = time_shift + local_duration * self.minStep)
                            melodies.notes.append(i_note)
                            prev = note
                            time_shift += local_duration * self.minStep
                            local_duration = 1
                if prev != rest_pitch:
                    i_note = pyd.Note(velocity = 100, pitch = prev, 
                                start = time_shift, end = time_shift + local_duration * self.minStep)
                    melodies.notes.append(i_note)
                gen_midi.instruments.append(melodies)
                gen_midi.write(output)
                print("finish render midi on " + output)

In [11]:
import pretty_midi as pyd
#from loader.dataloader import MIDI_Render

 
inpaint = np.concatenate(np.concatenate(np.load('res-exp-sketchnet_control_mixture_2.npy', allow_pickle= True)[0]['inpaint']))
#inpaint = irish_train[0]['notes']
render = MIDI_Render('Irish')
inpaint_midi = render.gd2midi(inpaint)

finish render midi on test.mid


In [12]:
inpaint = np.concatenate(np.concatenate(np.load('res-exp-sketchnet_control_mixture_2.npy', allow_pickle= True)[0]['inpaint']))
print(inpaint)

[ 72 128 128  68 128 128  72 128 128  72 128 128  75 128 128  72 128 128
  73 128 128  73 128 128  64 128 128 128  65 128  53 128 128 128 128 128
 128 128 128 128 128 128 128 128 128 128 128 128 128 128 128  66 128 128
  70 128 128  68 128 128 128 128 128  66 128 128  70 128 128  65 128 128
  65 128 128 128 128 128  65 128 128  66 128 128 128 128 128 128 128 128
 128 128 128 128 128 128]


In [13]:
result = list(np.load('generation_result_npy/res-validate-irish-sketchnet.npy', allow_pickle= True))[0]

In [14]:
list(result['past'])

[array([[ 70, 128, 128, 128, 128, 128, 128, 128, 128,  72, 128, 128,  73,
         128, 128,  72, 128, 128,  73, 128, 128,  75, 128, 128],
        [ 77, 128, 128, 128, 128, 128,  75, 128, 128,  80, 128, 128,  80,
         128, 128,  77, 128, 128,  75, 128, 128,  78, 128, 128],
        [ 77, 128, 128,  73, 128, 128,  70, 128, 128,  72, 128, 128,  73,
         128, 128,  75, 128, 128,  77, 128, 128,  79, 128, 128],
        [ 80, 128, 128, 128, 128, 128,  82, 128, 128,  79, 128, 128,  80,
         128, 128,  77, 128, 128,  75, 128, 128,  72, 128, 128],
        [ 70, 128, 128, 128, 128, 128, 128, 128, 128,  72, 128, 128,  73,
         128, 128,  72, 128, 128,  73, 128, 128,  75, 128, 128],
        [ 77, 128, 128, 128, 128, 128,  75, 128, 128,  80, 128, 128,  80,
         128, 128,  77, 128, 128,  75, 128, 128,  78, 128, 128]]),
 array([[ 70, 128, 128, 128, 128, 128, 128, 128, 128,  72, 128, 128,  73,
         128, 128,  72, 128, 128,  73, 128, 128,  75, 128, 128],
        [ 77, 128, 128, 1

In [15]:
print(len(result['past']), len(result['future']), len(result['inpaint']), len(result['gd']))

32 32 32 32


In [16]:
def render_list (list, i):
    render = MIDI_Render('Irish')
    render.gd2midi(np.concatenate(list['past'][i]), output='past.mid')
    render.gd2midi(np.concatenate(list['future'][i]), output='future.mid')
    render.gd2midi(np.concatenate(list['inpaint'][i]), output='inpaint.mid')
    render.gd2midi(np.concatenate(list['gd'][i]), output='gd.mid')

        

In [17]:
render_list(result, 16)

finish render midi on past.mid
finish render midi on future.mid
finish render midi on inpaint.mid
finish render midi on gd.mid


In [18]:
output = np.load('res-exp-sketchnet_control_mixture_2.npy', allow_pickle= True)

In [19]:
len(output)

300

In [20]:
list(output).keys()

AttributeError: 'list' object has no attribute 'keys'

In [ ]:
list(output)[2].keys()

dict_keys(['past1', 'past2', 'future1', 'future2', 'inpaint', 'gd1', 'gd2', 'acc', 'nll'])

In [99]:

validate = np.load("data/irish-dis-measure-vae-validate-repetition.npy", allow_pickle= True)


In [ ]:
import torch
import os
import numpy as np
from torch import optim
from torch.nn import functional as F
from SketchVAE.sketchvae import SketchVAE
from torch import optim
from torch.utils.data import Dataset, DataLoader, TensorDataset
from torch.distributions import Normal
from SketchNet.sketchnet import SketchNet
from utils.helpers import *
import time
###############################
# initial parameters
s_dir = ""
zp_dims = 128
zr_dims = 128
pf_dims = 512
gen_dims = 1024
combine_dims = 512
combine_head = 4
combine_num = 4
pf_num = 2
inpaint_len = 4
seq_len = 16
total_len = 16
batch_size = 1
n_epochs = 15
data_path = [
    s_dir + "data/irish-dis-measure-vae-train-whole.npy",
    s_dir + "data/irish-dis-measure-vae-validate-whole.npy",
    s_dir + "data/irish-dis-measure-vae-validate-repetition.npy",
    s_dir + "data/irish-dis-measure-vae-validate-non-repetition.npy"
]
lr = 1e-4
decay = 0.9999
##############################
##############  for vae init ##############
vae_hidden_dims = 1024
vae_zp_dims = 128
vae_zr_dims = 128
vae_beta = 0.1
vae_input_dims = 130
vae_pitch_dims = 129
vae_rhythm_dims = 3
vae_seq_len = 6 * 4
vae_beat_num = 4
vae_tick_num = 6
############################


In [ ]:
import torch

def processed_data_tensor(data):
    print("processed data:")
    gd = [] 
    px = []
    rx = []
    len_x = []
    nrx = []
    total = 0
    for i, d in enumerate(data):
        gd.append([list(dd[0]) for dd in d])
        px.append([list(dd[1]) for dd in d])
        rx.append([list(dd[2]) for dd in d])
        len_x.append([dd[3] for dd in d])
        if len(gd[-1][-1]) != vae_seq_len:
            gd[-1][-1].extend([128] * (vae_seq_len - len(gd[-1][-1])))
            px[-1][-1].extend([128] * (vae_seq_len - len(px[-1][-1])))
            rx[-1][-1].extend([2] * (vae_seq_len - len(rx[-1][-1])))
    for i,d in enumerate(len_x):
        for j,dd in enumerate(d):
            if len_x[i][j] == 0:
                gd[i][j][0] = 60
                px[i][j][0] = 60
                rx[i][j][0] = 1
                len_x[i][j] = 1
                total += 1
    gd = np.array(gd)
    px = np.array(px)
    rx = np.array(rx)
    len_x = np.array(len_x)
    for d in rx:
        nnrx = []
        for dd in d:
            temp = np.zeros((vae_seq_len, vae_rhythm_dims))
            lins = np.arange(0, len(dd))
            temp[lins, dd - 1] = 1
            nnrx.append(temp)
        nrx.append(nnrx)
    nrx = np.array(nrx)
    gd = torch.from_numpy(gd).long()
    px = torch.from_numpy(px).long()
    rx = torch.from_numpy(rx).float()
    len_x = torch.from_numpy(len_x).long()
    nrx = torch.from_numpy(nrx).float()
    print("processed finish! zeros:", total)
    print(gd.size(),px.size(),rx.size(),len_x.size(),nrx.size())
    return TensorDataset(px, rx, len_x, nrx, gd)


In [100]:
data = np.asarray(validate[0])

In [106]:
data[0]

array([array([ 74, 128, 128, 128, 128, 128,  76, 128, 128, 128, 128, 128,  72,
              128,  71, 128,  69, 128,  69, 128, 128, 128,  71, 128])         ,
       array([ 74,  76,  72,  71,  69,  69,  71, 128, 128, 128, 128, 128, 128,
              128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128])         ,
       array([1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2,
              1, 2])                                                           ,
       7], dtype=object)

In [ ]:
np.asarray([validate[0]])

array([[[array([ 58, 128, 128,  65, 128, 128,  68, 128, 128,  70, 128, 128, 128,
                128, 128,  68, 128, 128,  65, 128, 128,  66, 128, 128])         ,
         array([ 58,  65,  68,  70,  68,  65,  66, 128, 128, 128, 128, 128, 128,
                128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128])         ,
         array([1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1,
                2, 2])                                                           ,
         7],
        [array([128, 128, 128,  65, 128, 128,  63, 128, 128,  61, 128, 128, 128,
                128, 128,  60, 128, 128,  61, 128, 128,  63, 128, 128])         ,
         array([ 65,  63,  61,  60,  61,  63, 128, 128, 128, 128, 128, 128, 128,
                128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128])         ,
         array([2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1,
                2, 2])                                                           ,
     

In [ ]:
validate[0]

array([[array([ 58, 128, 128,  65, 128, 128,  68, 128, 128,  70, 128, 128, 128,
               128, 128,  68, 128, 128,  65, 128, 128,  66, 128, 128])         ,
        array([ 58,  65,  68,  70,  68,  65,  66, 128, 128, 128, 128, 128, 128,
               128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128])         ,
        array([1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1,
               2, 2])                                                           ,
        7],
       [array([128, 128, 128,  65, 128, 128,  63, 128, 128,  61, 128, 128, 128,
               128, 128,  60, 128, 128,  61, 128, 128,  63, 128, 128])         ,
        array([ 65,  63,  61,  60,  61,  63, 128, 128, 128, 128, 128, 128, 128,
               128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128])         ,
        array([2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1,
               2, 2])                                                           ,
        6],
      

In [ ]:
test = np.load(data_path[0], allow_pickle= True)

In [ ]:
test[0]

{'name': 'sessiontune25255',
 'raw': '',
 'notes': [77,
  128,
  128,
  80,
  128,
  128,
  80,
  128,
  128,
  128,
  128,
  128,
  82,
  128,
  128,
  80,
  128,
  128,
  77,
  128,
  128,
  82,
  128,
  128,
  80,
  128,
  128,
  77,
  128,
  128,
  75,
  128,
  128,
  77,
  128,
  128,
  73,
  128,
  128,
  70,
  128,
  128,
  70,
  128,
  128,
  70,
  128,
  128,
  77,
  128,
  128,
  80,
  128,
  128,
  80,
  128,
  128,
  128,
  128,
  128,
  82,
  128,
  128,
  80,
  128,
  128,
  77,
  128,
  128,
  82,
  128,
  128,
  80,
  128,
  128,
  77,
  128,
  128,
  75,
  128,
  128,
  77,
  128,
  128,
  75,
  128,
  128,
  77,
  128,
  128,
  73,
  128,
  128,
  75,
  128,
  128,
  77,
  128,
  128,
  80,
  128,
  128,
  80,
  128,
  128,
  128,
  128,
  128,
  82,
  128,
  128,
  80,
  128,
  128,
  77,
  128,
  128,
  82,
  128,
  128,
  80,
  128,
  128,
  77,
  128,
  128,
  75,
  128,
  128,
  77,
  128,
  128,
  73,
  128,
  128,
  70,
  128,
  128,
  70,
  128,
  128,
  68,
 

In [ ]:
dis_data_path = [
    "data/irish-dis-measure-vae-train-whole.npy",
    "data/irish-dis-measure-vae-validate-whole.npy",
    "data/irish-dis-measure-vae-test-whole.npy"
]

In [ ]:
dis_test = np.load(dis_data_path[0], allow_pickle= True)

In [ ]:
dis_test.shape



(39798, 16, 4)

In [81]:
result = list(np.load('generation_result_npy/res-validate-irish-sketchnet.npy', allow_pickle= True))[0]

In [83]:
result.keys()

dict_keys(['past', 'future', 'inpaint', 'gd', 'acc', 'nll'])

In [94]:
result['future'][0]

array([[ 77, 128, 128,  73, 128, 128,  70, 128, 128,  72, 128, 128,  73,
        128, 128,  75, 128, 128,  77, 128, 128,  79, 128, 128],
       [ 80, 128, 128, 128, 128, 128,  82, 128, 128,  79, 128, 128,  80,
        128, 128,  77, 128, 128,  75, 128, 128,  72, 128, 128],
       [ 70, 128, 128, 128, 128, 128, 128, 128, 128,  72, 128, 128,  73,
        128, 128,  72, 128, 128,  73, 128, 128,  75, 128, 128],
       [ 77, 128, 128, 128, 128, 128,  75, 128, 128,  80, 128, 128,  80,
        128, 128,  77, 128, 128,  75, 128, 128,  78, 128, 128],
       [ 77, 128, 128,  73, 128, 128,  70, 128, 128,  72, 128, 128,  73,
        128, 128,  75, 128, 128,  77, 128, 128,  79, 128, 128],
       [ 80, 128, 128,  77, 128, 128,  75, 128, 128,  72, 128, 128,  73,
        128, 128,  70, 128, 128,  70, 128, 128, 128, 128, 128]])